import { useEffect, useState } from 'react'
import { api, type ModelsResponse } from '../api/client'
import { UnavailableNotice } from '../components/UnavailableNotice'

const KNOWN_MODELS = ['logistic_regression', 'random_forest', 'xgboost']

export function ModelPerformance() {
  const [models, setModels] = useState<ModelsResponse | null>(null)
  const [metricsByModel, setMetricsByModel] = useState<Record<string, Record<string, unknown> | null>>({})

  useEffect(() => {
    api.models().then(setModels).catch(() => setModels({ status: 'unavailable', models: [] }))
    KNOWN_MODELS.forEach((name) => {
      api
        .modelMetrics(name)
        .then((res) => setMetricsByModel((prev) => ({ ...prev, [name]: res.status === 'ok' ? res.metrics! : null })))
        .catch(() => setMetricsByModel((prev) => ({ ...prev, [name]: null })))
    })
  }, [])

  const anyReady = Object.values(metricsByModel).some((m) => m !== null && m !== undefined)

  return (
    <div className="space-y-6">
      <h2 className="text-sm font-semibold uppercase tracking-wide text-slate-400">
        Model performance
      </h2>

      {models?.status === 'unavailable' && (
        <UnavailableNotice detail="No trained models found. Run `python -m src.models.train`." />
      )}

      {!anyReady && models?.status === 'ok' && (
        <UnavailableNotice detail="Models are registered but metrics have not been generated yet." />
      )}

      {anyReady && (
        <div className="overflow-hidden rounded-lg border border-white/10">
          <table className="w-full text-left text-xs">
            <thead className="bg-white/[0.04] text-slate-400">
              <tr>
                <th className="px-3 py-2">Model</th>
                <th className="px-3 py-2">Accuracy</th>
                <th className="px-3 py-2">Precision</th>
                <th className="px-3 py-2">Recall</th>
                <th className="px-3 py-2">F1</th>
                <th className="px-3 py-2">ROC-AUC</th>
                <th className="px-3 py-2">PR-AUC</th>
              </tr>
            </thead>
            <tbody>
              {KNOWN_MODELS.map((name) => {
                const m = metricsByModel[name]
                return (
                  <tr key={name} className="border-t border-white/5">
                    <td className="px-3 py-2 font-mono">{name}</td>
                    {['accuracy', 'precision', 'recall', 'f1', 'roc_auc', 'pr_auc'].map((key) => (
                      <td key={key} className="px-3 py-2">
                        {m && m[key] != null ? Number(m[key]).toFixed(3) : 'N/A'}
                      </td>
                    ))}
                  </tr>
                )
              })}
            </tbody>
          </table>
        </div>
      )}

      <p className="text-xs text-slate-500">
        Metrics are read directly from <code>results/model_metrics.json</code>, generated by{' '}
        <code>python -m src.models.train</code>. No number on this page is hardcoded — see{' '}
        <code>backend/main.py::model_metrics</code>.
      </p>
    </div>
  )
}
